export const GET_PRODUCTS_LIST = "GET_PRODUCTS_LIST";

export const STORE_PRODUCTS_LIST = "STORE_PRODUCTS_LIST";

export const ERROR_PRODUCT_LIST = "PRODUCTS_LIST_ERROR";

export const GET_PRODUCT_DETAILS = "GET_PRODUCT_DETAILS";

export const STORE_PRODUCT_DETAILS = "STORE_PRODUCT_DETAILS";

export const ERROR_PRODUCT_DETAILS = "PRODUCT_DETAILS_ERROR";
