export const GET_PRODUCTS_LIST = "GET_PRODUCTS_LIST";

export const STORE_PRODUCTS_LIST = "STORE_PRODUCTS_LIST";

export const ERROR_PRODUCT_LIST = "PRODUCTS_LIST_ERROR";

export const GET_PRODUCT_DETAILS = "GET_PRODUCT_DETAILS";

export const STORE_PRODUCT_DETAILS = "STORE_PRODUCT_DETAILS";

export const ERROR_PRODUCT_DETAILS = "PRODUCT_DETAILS_ERROR";

export const PRODUCT_DELETE_REQUEST = "PRODUCT_DELETE_REQUEST";

export const PRODUCT_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS";

export const PRODUCT_DELETE_FAIL = "PRODUCT_DELETE_FAIL";

export const PRODUCT_CREATE_REQUEST = "PRODUCT_CREATE_REQUEST";

export const PRODUCT_CREATE_SUCCESS = "PRODUCT_CREATE_SUCCESS";

export const PRODUCT_CREATE_FAIL = "PRODUCT_CREATE_FAIL";

export const PRODUCT_CREATE_RESET = "PRODUCT_CREATE_RESET";

export const PRODUCT_UPDATE_REQUEST = "PRODUCT_UPDATE_REQUEST";

export const PRODUCT_UPDATE_SUCCESS = "PRODUCT_UPDATE_SUCCESS";

export const PRODUCT_UPDATE_FAIL = "PRODUCT_UPDATE_FAIL";

export const PRODUCT_UPDATE_RESET = "PRODUCT_UPDATE_RESET";
